---
title: "BP Energy Dataset"
output: html_notebook
---

# Packages

```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(readr)
library(readxl)
library(purrr)
library(janitor)
library(rlang)
library(RMariaDB)
```

# Download

```{r}
try(dir.create("data-raw"))

bp_url <- "https://www.bp.com/content/dam/bp/business-sites/en/global/corporate/xlsx/energy-economics/statistical-review/bp-stats-review-2019-all-data.xlsx"

bp_xlsx <- "data-raw/bp-stats-review-2019-all-data.xlsx"

if (!file.exists(bp_xlsx)) {
  download.file(bp_url, bp_xlsx , method = "wget")
}
```

# Functions

```{r}
read_sheet_type1 <- function(x,y,z,t) {
  read_excel(
    "data-raw/bp-stats-review-2019-all-data.xlsx", 
    sheet = x,
    range = y,
    trim_ws = TRUE
  ) %>% 
    clean_names() %>% 
    gather("year", "value", -{{z}}) %>% 
    mutate(
      year = as.integer(str_replace(year, "x", "")),
      value = as.numeric(value),
      unit = z,
      category = t,
      sheet = x
    ) %>% 
    drop_na(value) %>% 
    rename(country = {{z}}) %>% 
    filter(!str_sub(country, 1, 5) %in% c("Total","Other"))
}

filter_and_export <- function(x) {
  y <- make_clean_names(x)
  
  f <- sprintf("data-clean/%s.csv", y)
  
  if (!file.exists(f)) {
    d <- d2 %>% 
      filter(category == y)
    
    write_csv(d, f)
  }
}
```

# Type 1 Data

```{r}
type1_sheets <- c(
  # Primary
  "Primary Energy Consumption",
  "Primary Energy - Cons capita",
  
  # Oil
  "Oil - Proved reserves history",
  "Oil Production - Barrels",
  "Oil Production - Tonnes",
  "Oil Production - Crude Conds",
  "Oil Production - NGLs",
  "Oil Consumption - Barrels",
  "Oil Consumption - Tonnes",
  "Oil Consumption - Mtoe",
  "Oil - Refinery throughput",
  "Oil - Refining capacity",

  # Gas
  "Gas - Proved reserves history ",
  "Gas Production - Bcm",
  "Gas Production - Bcf",
  "Gas Production - Mtoe",
  "Gas Consumption - Bcm",
  "Gas Consumption - Bcf",
  "Gas Consumption - Mtoe",
  "Gas - LNG imports",
  "Gas - LNG exports",
  
  # Coal
  "Coal Production - Tonnes",
  "Coal Production - Mtoe",
  
  # Nuclear
  "Nuclear Generation - TWh",
  "Nuclear Consumption - Mtoe",
  
  # Hydro
  "Hydro Generation - TWh",
  "Hydro Consumption - Mtoe",
  
  # Renewables
  "Renewables - TWh",
  "Renewables - Mtoe",
  
  # Solar
  "Solar Generation - TWh",
  "Solar Consumption - Mtoe",
  
  # Wind
  "Wind Generation - TWh ",
  "Wind Consumption - Mtoe",
  
  # Geo
  "Geo Biomass Other - TWh",
  "Geo Biomass Other - Mtoe",
  
  # Bio
  "Biofuels Production - Kboed",
  "Biofuels Production - Ktoe",
  
  # Electricity
  "Electricity Generation ",
  "Elec Gen from Oil",
  "Elec Gen from Gas",
  "Elec Gen from Coal",
  "Elec Gen from Other",
  
  # CO2 emissions
  "Carbon Dioxide Emissions",
  
  # Cobalt
  "Cobalt Production-Reserves",
  
  # Lithium
  "Lithium Production-Reserves",
  
  # Graphite
  "Graphite Production-Reserves",
  
  # Rare earth
  "Rare Earth Production-Reserves",
  
  # Geothermal capacity
  "Geothermal Capacity",
  
   # Solar capacity
  "Solar Capacity",
  
  # Wind capacity
  "Wind Capacity"
)
```

```{r}
type1_ranges <- c(
  # Primary
  "A3:BC109",
  "A3:BC109",
  
  # Oil
  "A3:AN73",
  "A3:BC73",
  "A3:BC73",
  "A3:T72",
  "A3:T72",
  "A3:BC109",
  "A3:BC109",
  "A3:BC109",
  "A3:AN97",
  "A3:BC97",
  
  # Gas
  "A3:AN75",
  "A3:AX73",
  "A3:AX73",
  "A3:AX73",
  "A3:BC109",
  "A3:BC109",
  "A3:BC109",
  "A3:T38",
  "A3:T31",
  
  # Coal
  "A3:AM57",
  "A3:AM57",
  
  # Nuclear
  "A3:BC109",
  "A3:BC109",
  
  # Hydro
  "A3:BC109",
  "A3:BC109",
  
  #Renewables
  "A3:BC109",
  "A3:BC109",
  
  # Solar
  "A3:BC109",
  "A3:BC109",
  
  # Wind
  "A3:BC109",
  "A3:BC109",
  
  # Geo
  "A3:BC109",
  "A3:BC109",
  
  # Bio
  "A3:AD44",
  "A3:AD44",
  
  # Electricity
  "A3:AI108",
  "A3:AI53",
  "A3:AI53",
  "A3:AI53",
  "A3:AI53",
  
  # CO2 emissions
  "A3:BC109",
  
  # Cobalt
  "A3:Y17",
  
  # Lithium
  "A3:Y13",
  
  # Graphite
  "A3:Y16",
  
  # Rare earth
  "A3:Y13",
  
  # Geothermal capacity
  "A4:Y43",
  
  # Solar capacity
  "A4:X69",
  
  # Wind capacity
  "A4:Y41"
)
```

```{r}
type1_dimensions <- c(
  # Primary
  "million_tonnes_oil_equivalent",
  "gigajoule_per_capita",
  
  # Oil
  "thousand_million_barrels",
  "thousand_barrels_daily",
  "million_tonnes",
  "thousand_barrels_daily",
  "thousand_barrels_daily",
  "thousand_barrels_daily",
  "million_tonnes",
  "million_tonnes_oil_equivalent",
  "thousand_barrels_daily",
  "thousand_barrels_daily",
  
  # Gas
  "trillion_cubic_metres",
  "billion_cubic_metres",
  "billion_cubic_feet_per_day",
  "million_tonnes_oil_equivalent",
  "billion_cubic_metres",
  "billion_cubic_feet_per_day",
  "million_tonnes_oil_equivalent",
  "billion_cubic_metres",
  "billion_cubic_metres",
  
  # Coal
  "million_tonnes",
  "million_tonnes_oil_equivalent",
  
  # Nuclear
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Hydro
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Renewables
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Solar
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Wind
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Geo
  "terawatt_hours",
  "million_tonnes_oil_equivalent",
  
  # Bio
  "thousand_b_doe",
  "thousand_tonnes_oil_equivalent",
  
  # Electricity
  "terawatt_hours",
  "terawatt_hours",
  "terawatt_hours",
  "terawatt_hours",
  "terawatt_hours",
  
  # CO2 emissions
  "million_tonnes_of_carbon_dioxide",
  
  # Cobalt
  "thousand_tonnes",
  
  # Lithium
  "thousand_tonnes_of_lithium_content",
  
  # Graphite
  "thousand_tonnes",
  
  # Rare earth
  "thousand_tonnes1",
  
  # Geothermal capacity
  "megawatts",
  
  # Solar capacity
  "megawatts",
  
  # Wind capacity
  "megawatts"
)
```

```{r}
d1 <- pmap(list(type1_sheets, type1_ranges, type1_dimensions, make_clean_names(type1_sheets)), read_sheet_type1)
```

# Country names

```{r}
countries_csv <- "data-raw/country_name_tool_countryname.csv"

if (!file.exists(countries_csv)) {
  # Connect to my-db as defined in ~/.my.cnf
  con <- dbConnect(RMariaDB::MariaDB())
  owid_countries <- tbl(con, "country_name_tool_countryname") %>% collect()
  write_csv(owid_countries, countries_csv)
} else {
  owid_countries <- read_csv(countries_csv)
}
```

```{r}
d2 <- bind_rows(d1)

d2 <- d2 %>% 
  mutate(country = case_when(
    country == "US" ~ "usa",
    country == "Rest of World" ~ "Rest of the World",
    country == "Rest of World2" ~ "Rest of the World",
    country == "Rest of World3" ~ "Rest of the World",
    country == "Brazil1" ~ "Brazil",
    country == "India2" ~ "India",
    country == "Republic of Congo" ~ "Congo (Republic of)",
    TRUE ~ country
  ))

countries_exclude <- c("Central America", "Eastern Africa", "Middle Africa", "Western Africa",
                      "Rest of Europe")

d2 <- d2 %>% 
  filter(!country %in% countries_exclude) %>% 
  rename(country_name = country)

country_to_code <- d2 %>% 
  select(country_name) %>% 
  distinct() %>% 
  left_join(owid_countries, by = "country_name")

d2 <- d2 %>% 
  left_join(country_to_code) %>% 
  select(starts_with("country"), id, owid_country, everything())
```

# Save

```{r}
try(dir.create("data-clean"))

map(type1_sheets, filter_and_export)
```
